### ISSUE TITLE
0.0.7 alfredworkflow release is broken

### ISSUE THREAD

**Issue by brentchow** [briangonzalez/alfred-messages#14]
When downloading and installing the [released 0.0.7 Messages.alfredworkflow](https://github.com/briangonzalez/alfred-messages/releases/tag/0.0.7), there is an error in the "run script" step that causes:

![image](https://user-images.githubusercontent.com/3849502/57322698-248a5780-70d2-11e9-99f9-0e347a0e79be.png)

The run script appears to have been compiled improperly and is attempting to call a bin script in node_modules:

```js
./node_modules/.bin/run-node lib/send-message.js "$1"
```

**Comment by brentchow** [comment]
This workflow requires Node and if you used an alternative installation method such as `nvm`, you'll need to follow these steps to make this workflow work: https://github.com/moranje/alfred-workflow-todoist#non-standard-node-installation

These installation instructions should be added to the README.md.

**Comment by feppos0** [comment]
hi! love the workflow, but I'm not able to update from 0.0.7 to 0.1.0 via npm, is it possible to add it as a .workflow on GitHub?

**Comment by briangonzalez** [comment]
Rewritten and released as 1.0.0. Grab it via NPM or from the Releases tab!
